#!/bin/bash

folders=" "
folders+="$(dirname $HOME) $HOME $HOME/.config "
folders+="$HOME/Workspaces "
folders+="$HOME/Workspaces/personal "
folders+="$HOME/Workspaces/HK6 "

selected=$(find $folders -mindepth 1 -maxdepth 1 -type d | fzf)
if [[ -z $selected ]]; then
    exit 0
fi

bn_selected=$(basename "$selected" | tr . _ | tr '[:upper:]' '[:lower:]')
bn_parent=$(basename $(dirname "$selected") | tr . _ | tr '[:upper:]' '[:lower:]')
tmux_running=$(pgrep tmux)

# create window instead of session
windows_array=("_config" "personal")
if [[ ${windows_array[@]} == *"$bn_parent"* ]]; then
    target="$bn_parent:$bn_selected"
    tmux switch-client -t $target || \
        tmux neww -n $bn_selected -t "$bn_parent:" -c $selected && \
            tmux switch-client -t $target
    exit 0
fi

# create new session
if [[ -z $TMUX ]] && [[ -z $tmux_running ]]; then
    tmux new-session -s $bn_selected -c $selected
    exit 0
fi

if ! tmux has-session -t=$bn_selected 2> /dev/null; then
    tmux new-session -ds $bn_selected -c $selected
fi

# switch client
tmux switch-client -t $bn_selected
