#!/bin/bash

if [[ $# -eq 1 ]]; then
    selected=$1
else
    session_path=$(tmux display-message -p "#{session_path}")
    selected=$(find $session_path -mindepth 1 -maxdepth 3 -type d | fzf)
fi

if [[ -z $selected ]]; then
    exit 0
fi

selected_name=$(basename "$selected" | tr . _ | tr '[:upper:]' '[:lower:]')
tmux_running=$(pgrep tmux)
session_name=$(tmux display-message -p "#S")
target="$session_name:$selected_name"

# if [[ -z $TMUX ]] && [[ -z $tmux_running ]]; then
#     tmux new-session -s $selected_name -c $selected
#     exit 0
# fi
#
# tmux attach-session -t '$session_name:$selected_name'
# if ! tmux has-session -t='$session_name' 2> /dev/null; then
#     tmux new-session -ds $selected_name -c $selected
# fi

tmux switch-client -t $target || tmux neww -n $selected_name -c $selected

