#!/usr/bin/env sh

if [[ $# -eq 1 ]]; then
    selected=$1
else
    folders="/home /home/uit/.config /run/media/learning/CLASS/HK5 /run/media/learning /run/media/learning/code "
    selected=$(find $folders -mindepth 1 -maxdepth 1 -type d | fzf)
    if [[ -z $selected ]]; then
        exit 0
    fi
fi


selected_name=$(basename "$selected" | tr . _ | tr '[:upper:]' '[:lower:]')
tmux_running=$(pgrep tmux)
parent=$(dirname "$selected")

if [[ $parent == "/home/uit/.config" ]]; then
    parent_name=$(basename "$parent" | tr . _ | tr '[:upper:]' '[:lower:]')
    target="$parent_name:$selected_name"
    tmux switch-client -t $target || \
        tmux neww -n $selected_name -t "$parent_name:" -c $selected && \
        tmux switch-client -t $target
    exit 0
fi

if [[ -z $TMUX ]] && [[ -z $tmux_running ]]; then
    tmux new-session -s $selected_name -c $selected
    exit 0
fi

if ! tmux has-session -t=$selected_name 2> /dev/null; then
    tmux new-session -ds $selected_name -c $selected
fi

tmux switch-client -t $selected_name
